name: tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  tests:
    strategy:
      matrix:
        python: [3.8, 3.9]
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      - name: Install system dependencies
        run: sudo apt-get install -y poppler-utils
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run all files
        run: |
          python3 docsum.py docs/declaration.txt
          python3 docsum.py docs/2023.findings-emnlp.945.pdf
          python3 docsum.py docs/hamlet.txt
          python3 docsum.py docs/estados-unidos-admite-haber-perdido-la-pista-de-32000-menores-migrantes-no-acompanados.html
          python3 docsum.py docs/news-mx.txt
          python3 docsum.py docs/constitution-mx.txt
